class NeuralNetworkExecutor:
    """Allows the evaluation of a given game state. Coordinates requests from different threads.

    This is essentially a wrapper for a neural network instance with fixed weights
    that sole purpose is to be executed for different game states.

    The class can for example transparently handle batch execution of the network by blocking
    calls to evaluate game states until a full batch is reached."""
    def __init__(self, configured_nn):
        # TODO: How is the network configuration passed? Is it simply an instance?
        # No matter what it is, it's once configured and then stays the same for the
        # lifetime of the object!
        self.configured_nn = configured_nn

    def execute(self, game_state):
        """Executes a neural network to evaluate a given game state.

        Returns the evaluation generated by the network.
        Might block for a while because other evaluations are being performed."""
        raise NotImplementedError("Add network execution.")


class NeuralNetwork:
    """Wrapper that represents a single neural network instance.

    This is intended to abstract away the actual creation, training and execution of the neural network.
    This should hopefully also allow to re-use major parts of the code for different network structures."""
    def construct_network(self):
        raise NotImplementedError("Add the construction of your custom graph structure.")

    def init_network(self):
        raise NotImplementedError("Run initialisation code for your network.")

    def execute_batch(self, game_states):
        raise NotImplementedError("Add implementation that takes game_states and executes them as a batch.")

    def train_batch(self, game_states, outputs):
        raise NotImplementedError("Add implementation that executes one batch training step.")

    def save_weights(self, filename):
        raise NotImplementedError("Add implementation that saves the weights of this network to a checkpoint.")

    def load_weights(self, filename):
        raise NotImplementedError("Add implementation that loads the weights of this network to a checkpoint.")

    def log_loss(self, tf_file_writer, game_states, outputs):
        raise NotImplementedError("Add implementation to write average losses to the stats file and return them.")


class MCTSExecutor:
    """Handles the simulation of MCTS in one specific game state.

    This excludes actually progressing the game. The sole purpose of this class
    is to run a specific number of simulation steps starting at a given game state.

    It then returns the target move probabilities and the target value of the given game sate."""
    # TODO: Initialisation and Reuse of older runs
    # TODO: pass game state and NNExecutor on init

    def run(self, n_simulations):
        raise NotImplementedError("Run #n_simulations simulation steps on the tree and return an target evaluation.")


class SelfplayExecutor:
    """Handles the simulation one selfplay game.

    This should run one game of selfplay and return a list of all states and all
    corresponding probability/value targets that can then be used as training data."""
    # TODO: pass game state and NNExecutor on init
    # TODO: pass simulation runs

    def run(self):
        raise NotImplementedError("Run simulation and return target evaluations.")


class TrainingExecutor:
    """Manages the training process of a neural network.

    This is managing the training set, test set and training process.
    The class is given an initial weight configuration. It then is fed example data.
    It has to manage the example data internally, split it into a training and test set."""
    def add_examples(self, evaluations):
        raise NotImplementedError("Add the given examples to be managed and used for training.")

    def run_training_batch(self):
        raise NotImplementedError("Run a single training batch.")


class ModelEvaluator:
    """Compares two neural network configurations by playing out a small tournament."""
    # TODO: Pass neural networks and maps to be played

    def run(self, n_games):
        raise NotImplementedError("Play a tournament with #n_games. Return the win-rate of the new network.")


class AITrivialEvaluator:
    """Compares a neural network to ai trivial by playing out a small tournament."""
    # TODO: Pass neural networks and maps to be played

    def run(self, n_games):
        raise NotImplementedError("Play a tournament with #n_games. Return the win-rate of the network.")


class Evaluation:
    """Holds a game state its evaluation.

    The evaluation consists of move probabilities and the expected result of the game state.

    Can be transformed to normal form and back.
    In normal form the currently active player is player one (this should make it easier for the nn)."""


